name: server-pipeline

on:
  push:
    branches: [server]

jobs:
  backend-CI:
    name: server-CI
    runs-on: ubuntu-latest

    steps:
      # 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # docker build 세팅
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.0.0

      # 캐시 받아오기
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # GitHub 컨테이너 레지스트리에 로그인
      - name: Login to ghcr
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io/whaleap
          username: ${{ github.actor }}
          password: ${{ secrets[format('GHCR_TOKEN_{0}', github.actor)] }}

      # .env 파일 생성
      - name: Set .env File
        run: |
          cd backend
          echo "SERVER_PORT= ${{secrets.SERVER_PORT}}" >> .env
          echo "DB_URL= ${{secrets.DB_URL}}" >> .env
          echo "REDIS_URL = ${{secrets.REDIS_URL}}" >> .env
          echo "CRYPTO_KEY= ${{secrets.CRYPTO_KEY}}" >> .env
          echo "CRYPTO_SALT=${{secrets.CRYPTO_SALT}}" >> .env
          echo "CRYPTO_ALGORITHM=${{secrets.CRYPTO_ALGORITHM}}" >> .env
          echo "SALT_ROUNDS= ${{secrets.SALT_ROUNDS}}" >> .env
          echo "SESSION_KEY= ${{secrets.SESSION_KEY}}" >> .env
          echo "NODEMAILER_USER= ${{secrets.NODEMAILER_USER}}" >> .env
          echo "NODEMAILER_PASS= ${{secrets.NODEMAILER_PASS}}" >> .env

      # 빌드 후 푸쉬
      - name: Build and push
        id: docker-build
        uses: docker/build-push-action@v3
        with:
          context: server
          file: ./server/Dockerfile
          push: true
          tags: "ghcr.io/whaleap/during-budget_server:latest"
          # (3)
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # 이전 캐시 지우고 새로운 캐시 옮기기
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  backend-CD:
    name: backend-CD
    needs: backend-CI
    runs-on: [self-hosted, label-go] # AWS ./configure에서 사용할 label명

    steps:
      # 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # GitHub 컨테이너 레지스트리에 로그인
      - name: Login to ghcr
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io/whaleap
          username: ${{ github.actor }}
          password: ${{ secrets[format('GHCR_TOKEN_{0}', github.actor)] }}

      # Pull images
      - name: Docker pull
        run: |
          docker pull ghcr.io/whaleap/during-budget_server:latest

      # Run containers
      - name: Docker run
        run: |
          docker rm -f during-budget_server_1 &>/dev/null && echo 'Removed old container'
          docker run --name during-budget_server_1  --restart on-failure -p ${{secrets.SERVER_PORT}}:${{secrets.SERVER_PORT}} -d ghcr.io/whaleap/during-budget_server:latest

      # 이전 이미지 삭제
      - name: Prune images
        run: |
          docker image prune -f
          docker images
